<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>Checkout | Aparatus Pastime</title>

  <link rel="icon" type="image/png" href="{{ asset('assets/logo.png') }}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700;800&family=Outfit:wght@400;500;600;700;800&display=swap"
    rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {
      theme: {
        extend: {
          colors: {
            'brand-blue': '#1261A0', 'brand-navy': '#073B73', 'brand-orange': '#F58220',
            'brand-bright-orange': '#FF9F1C', 'play-yellow': '#FFD447', 'sky-blue': '#7DD3FC',
            'mint': '#8FE3CF', 'soft-coral': '#FF8A80', 'purple-play': '#A78BFA',
            'warm-cream': '#FFFDF7', 'soft-blue': '#F0F8FF', 'soft-yellow': '#FFF9E6',
            'soft-mint': '#F0FFF9', 'soft-orange': '#FFF4EA', 'soft-purple': '#F5F3FF',
            'soft-sky': '#F0F9FF', 'dark-navy': '#172B4D', 'body-text': '#465466',
            'brand-muted': '#7A8795', 'brand-border': '#E8EDF2',
          },
          fontFamily: { sans: ['Nunito', 'sans-serif'], heading: ['Outfit', 'sans-serif'], body: ['Nunito', 'sans-serif'] }
        }
      }
    }
  </script>
  <link rel="stylesheet" href="{{ asset('assets/css/custom.css') }}">

  {{-- Begin-checkout tracking (inline
  <script> generated by PixelTracker)--}}
    {!! $beginCheckoutScript ?? '' !!}
</head >

      @php
        $codEnabled = $codEnabled ?? (bool) \App\Models\Setting::first()?->cod_enabled;
        $hasAddresses = $addresses->isNotEmpty();
        $selectedAddressId = $defaultAddress?->id ?? $addresses->first()?->id;
        $input = 'w-full px-3.5 py-2.5 bg-soft-blue/40 border border-brand-border rounded-xl focus:outline-none focus:border-brand-blue';
      @endphp

      <body class="bg-warm-cream text-body-text" >

  <header class="bg-white border-b border-brand-border py-3.5 shadow-2xs">
    <div class="max-w-7xl mx-auto px-4 flex items-center justify-between">
      <a href="{{ route('home') }}" class="flex items-center gap-2">
        <img src="{{ asset('assets/logo.png') }}" alt="Aparatus Pastime" class="h-10 w-auto">
      </a>
      <div class="flex items-center gap-2 text-xs font-bold font-heading text-emerald-700 bg-emerald-50 px-3.5 py-1.5 rounded-full border border-emerald-200">
        <i class="fa-solid fa-lock text-emerald-600"></i>
        <span>256-Bit SSL Encrypted Checkout</span>
      </div>
    </div>
  </header>

  <main class="py-8 md:py-12">
    <div class="max-w-7xl mx-auto px-4">
      <div class="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">

        <!-- LEFT -->
        <div class="lg:col-span-7 space-y-6">
          <form id="checkout-form" class="space-y-6" novalidate>

            <!-- Error box -->
            <div id="checkout-errors" class="hidden bg-red-50 border border-red-200 text-red-700 text-xs font-sans rounded-2xl p-4"></div>

            <!-- STEP 1: SHIPPING ADDRESS -->
            <div class="bg-white rounded-3xl border border-brand-border p-6 shadow-xs space-y-4">
              <div class="flex items-center gap-3 pb-3 border-b border-brand-border font-heading">
                <span class="w-7 h-7 rounded-full bg-brand-blue text-white text-xs font-bold flex items-center justify-center">1</span>
                <h2 class="font-bold text-base text-dark-navy">Shipping Address</h2>
              </div>

              @if ($hasAddresses)
                <div class="space-y-2">
                  <span class="text-[11px] font-bold uppercase tracking-wider text-brand-muted font-heading">SAVED ADDRESSES</span>
                  <div id="saved-address-cards" class="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    @foreach ($addresses as $addr)
                      @php $isSel = $addr->id === $selectedAddressId; @endphp
                      <label data-address-card data-id="{{ $addr->id }}" data-default="{{ $addr->is_default ? 1 : 0 }}"
                        class="block p-3 rounded-2xl border-2 cursor-pointer transition {{ $isSel ? 'border-brand-blue bg-soft-blue' : 'border-brand-border bg-white hover:border-brand-blue' }}">
                        <input type="radio" name="address_choice" value="{{ $addr->id }}" class="sr-only" {{ $isSel ? 'checked' : '' }}>
                        <div class="flex items-center justify-between text-xs font-bold font-heading mb-1">
                          <span class="text-dark-navy capitalize">{{ $addr->address_type ?? 'Home' }} · {{ $addr->name }}</span>
                          @if ($addr->is_default)
                            <span class="text-[10px] bg-brand-blue text-white px-2 py-0.5 rounded-full">Default</span>
                          @endif
                        </div>
                        <p class="text-[11px] text-body-text font-sans leading-relaxed">
                          {{ $addr->address_line_1 }}@if ($addr->address_line_2), {{ $addr->address_line_2 }}@endif,
                          {{ $addr->city?->name }}, {{ $addr->state?->name }} - {{ $addr->pincode }}<br>
                          <i class="fa-solid fa-phone text-[9px]"></i> {{ $addr->phone }}
                        </p>
                      </label>
                    @endforeach
                  </div>

                  <button type="button" id="toggle-new-address"
                    class="text-xs font-bold font-heading text-brand-blue hover:text-brand-orange transition cursor-pointer pt-1">
                    <i class="fa-solid fa-plus mr-1"></i>Add a new address
                  </button>
                </div>
              @endif

              <!-- New address form -->
              <div id="new-address-form" class="{{ $hasAddresses ? 'hidden' : '' }} grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs pt-2 font-sans">
                <div class="sm:col-span-2">
                  <label class="block font-bold text-dark-navy mb-1 font-heading">Full Name *</label>
                  <input type="text" name="name" value="{{ old('name', $customer->name) }}" placeholder="Full name" class="{{ $input }}">
                </div>
                <div>
                  <label class="block font-bold text-dark-navy mb-1 font-heading">Email *</label>
                  <input type="email" name="email" value="{{ old('email', $customer->email) }}" placeholder="name@example.com" class="{{ $input }}">
                </div>
                <div>
                  <label class="block font-bold text-dark-navy mb-1 font-heading">Phone *</label>
                  <input type="tel" name="phone" value="{{ old('phone', $customer->mobile ?? '') }}" placeholder="10-digit mobile" class="{{ $input }}">
                </div>
                <div class="sm:col-span-2">
                  <label class="block font-bold text-dark-navy mb-1 font-heading">Address Line 1 *</label>
                  <input type="text" name="address_line_1" placeholder="Flat No, Apartment, Street" class="{{ $input }}">
                </div>
                <div class="sm:col-span-2">
                  <label class="block font-bold text-dark-navy mb-1 font-heading">Address Line 2</label>
                  <input type="text" name="address_line_2" placeholder="Landmark (optional)" class="{{ $input }}">
                </div>
                <div>
                  <label class="block font-bold text-dark-navy mb-1 font-heading">State *</label>
                  <select name="state_id" id="state-select" class="{{ $input }}">
                    <option value="">Select state</option>
                    @foreach ($states as $state)
                      <option value="{{ $state->id }}">{{ $state->name }}</option>
                    @endforeach
                  </select>
                </div>
                <div>
                  <label class="block font-bold text-dark-navy mb-1 font-heading">City *</label>
                  <select name="city_id" id="city-select" class="{{ $input }}">
                    <option value="">Select state first</option>
                  </select>
                </div>
                <div>
                  <label class="block font-bold text-dark-navy mb-1 font-heading">PIN Code *</label>
                  <input type="text" name="pincode" maxlength="6" inputmode="numeric" placeholder="6-digit PIN" class="{{ $input }}">
                </div>
                <div>
                  <label class="block font-bold text-dark-navy mb-1 font-heading">Country</label>
                  <input type="text" value="India" readonly class="w-full px-3.5 py-2.5 bg-gray-100 border border-brand-border rounded-xl text-brand-muted cursor-not-allowed">
                </div>
                <div class="sm:col-span-2 flex flex-wrap items-center gap-3">
                  <button type="button" id="save-address-btn"
                    class="btn-play-blue text-xs font-heading font-bold py-2.5 px-5 rounded-xl cursor-pointer">
                    Save &amp; use this address
                  </button>
                  @if ($hasAddresses)
                    <button type="button" id="cancel-new-address" class="text-xs font-bold font-heading text-brand-muted hover:text-dark-navy cursor-pointer">Cancel</button>
                  @endif
                  <span class="text-[11px] text-brand-muted">Saving updates GST in your order summary.</span>
                </div>
              </div>
            </div>

            <!-- STEP 2: PAYMENT -->
            <div class="bg-white rounded-3xl border border-brand-border p-6 shadow-xs space-y-4">
              <div class="flex items-center gap-3 pb-3 border-b border-brand-border font-heading">
                <span class="w-7 h-7 rounded-full bg-brand-blue text-white text-xs font-bold flex items-center justify-center">2</span>
                <h2 class="font-bold text-base text-dark-navy">Payment Method</h2>
              </div>

              <div class="space-y-3 text-xs font-heading">
                <label data-pay-card class="flex items-center justify-between p-3.5 rounded-2xl border-2 border-brand-orange bg-soft-orange cursor-pointer transition">
                  <div class="flex items-center gap-3">
                    <input type="radio" name="payment_method" value="razorpay" checked class="text-brand-orange">
                    <div>
                      <span class="font-bold text-dark-navy block text-sm">Pay Online</span>
                      <span class="text-brand-muted text-[11px] font-sans">UPI, Credit / Debit Card, Net Banking via Razorpay</span>
                    </div>
                  </div>
                  <i class="fa-solid fa-credit-card text-brand-orange text-lg"></i>
                </label>

                @if ($codEnabled)
                  <label data-pay-card class="flex items-center justify-between p-3.5 rounded-2xl border border-brand-border bg-white hover:border-brand-blue cursor-pointer transition">
                    <div class="flex items-center gap-3">
                      <input type="radio" name="payment_method" value="cod" class="text-brand-blue">
                      <div>
                        <span class="font-bold text-dark-navy block text-sm">Cash on Delivery (COD)</span>
                        <span class="text-brand-muted text-[11px] font-sans">Pay at your doorstep upon arrival</span>
                      </div>
                    </div>
                    <i class="fa-solid fa-money-bill-wave text-emerald-600 text-lg"></i>
                  </label>
                @endif
              </div>
            </div>

            <button type="submit" id="place-order-btn"
              class="w-full btn-play-orange py-4 px-6 rounded-2xl text-base shadow-lg transition flex items-center justify-center gap-2 cursor-pointer font-heading disabled:opacity-60 disabled:cursor-not-allowed">
              <i class="fa-solid fa-circle-check"></i>
              <span id="place-order-label">COMPLETE &amp; PLACE ORDER</span>
            </button>
          </form>
        </div>

        <!-- RIGHT: SUMMARY -->
        <div class="lg:col-span-5 space-y-6 lg:sticky lg:top-8">
          <div class="bg-white rounded-3xl border border-brand-border p-6 shadow-xs space-y-4">
            <h3 class="font-heading font-bold text-sm uppercase tracking-wider text-dark-navy pb-3 border-b border-brand-border flex items-center justify-between">
              <span>BAG ITEMS SUMMARY</span>
              <a href="{{ route('cart') }}" class="text-xs text-brand-blue hover:text-brand-orange normal-case">Edit Bag</a>
            </h3>

            <div class="space-y-3 max-h-72 overflow-y-auto pr-1">
              @foreach ($cart->items as $item)
                @php
                  $img = ($item->imageVariant && $item->imageVariant->image)
                    ? asset('storage/' . $item->imageVariant->image)
                    : ($item->product?->display_image);

                  $variantLabel = null;
                  if (!empty($item->selected_attributes)) {
                    $variantLabel = collect($item->selected_attributes)->map(function ($v, $k) {
                      if (is_array($v)) {
                        return ($v['attribute'] ?? $v['name'] ?? $k) . ': ' . ($v['value'] ?? $v['label'] ?? reset($v));
                      }
                      return $k . ': ' . $v;
                    })->join(' · ');
                  }
                @endphp
                <div class="flex items-center gap-3 pb-2.5 border-b border-brand-border">
                  @if ($img)
                    <img src="{{ $img }}" alt="{{ $item->product?->name }}" class="w-12 h-12 object-contain bg-soft-blue rounded-xl p-1 border border-brand-border shrink-0">
                  @else
                    <div class="w-12 h-12 bg-soft-blue rounded-xl border border-brand-border shrink-0 flex items-center justify-center text-brand-muted"><i class="fa-solid fa-image"></i></div>
                  @endif
                  <div class="flex-1 min-w-0">
                    <h5 class="text-xs font-bold font-heading text-dark-navy truncate">{{ $item->product?->name ?? 'Product' }}</h5>
                    @if ($variantLabel)
                      <div class="text-[10px] text-brand-muted font-sans truncate">{{ $variantLabel }}</div>
                    @endif
                    <div class="text-[11px] text-brand-muted font-sans">Qty: {{ $item->quantity }} × ₹{{ number_format($item->price, 2) }}</div>
                    @foreach ($item->addons as $addon)
                      <div class="text-[10px] text-brand-muted font-sans truncate">+ {{ $addon->detail }} (₹{{ number_format($addon->price, 2) }})</div>
                    @endforeach
                  </div>
                  <span class="text-xs font-bold font-heading text-brand-navy">₹{{ number_format($item->total, 2) }}</span>
                </div>
              @endforeach
            </div>

            <div class="pt-4 border-t border-brand-border space-y-2.5 text-xs font-sans">
              <div class="flex justify-between text-body-text">
                <span>Subtotal</span>
                <span class="font-bold text-dark-navy font-heading">₹{{ number_format($cart->subtotal, 2) }}</span>
              </div>

              @if ($cart->discount > 0)
                <div class="flex justify-between text-emerald-600 font-bold font-heading">
                  <span>Discount @if ($cart->coupon_code)({{ $cart->coupon_code }})@endif</span>
                  <span>− ₹{{ number_format($cart->discount, 2) }}</span>
                </div>
              @endif

              @if ($cart->tax_amount > 0)
                @if ($cart->gst_type === 'igst' && $cart->igst_amount > 0)
                  <div class="flex justify-between text-body-text">
                    <span>IGST ({{ rtrim(rtrim(number_format($cart->igst_rate, 2), '0'), '.') }}%)</span>
                    <span class="font-heading font-bold">₹{{ number_format($cart->igst_amount, 2) }}</span>
                  </div>
                @else
                  @if ($cart->cgst_amount > 0)
                    <div class="flex justify-between text-body-text">
                      <span>CGST ({{ rtrim(rtrim(number_format($cart->cgst_rate, 2), '0'), '.') }}%)</span>
                      <span class="font-heading font-bold">₹{{ number_format($cart->cgst_amount, 2) }}</span>
                    </div>
                  @endif
                  @if ($cart->sgst_amount > 0)
                    <div class="flex justify-between text-body-text">
                      <span>SGST ({{ rtrim(rtrim(number_format($cart->sgst_rate, 2), '0'), '.') }}%)</span>
                      <span class="font-heading font-bold">₹{{ number_format($cart->sgst_amount, 2) }}</span>
                    </div>
                  @endif
                @endif
              @endif

              <div class="border-t border-brand-border pt-3 flex justify-between items-baseline font-heading">
                <span class="text-sm font-bold text-dark-navy">Total to Pay</span>
                <span class="text-2xl font-bold text-brand-navy">₹{{ number_format($cart->grand_total, 2) }}</span>
              </div>
            </div>

            <div class="p-3 bg-soft-blue rounded-2xl border border-blue-100 text-center text-xs text-brand-blue font-heading space-y-1">
              <div class="font-bold flex items-center justify-center gap-1.5">
                <i class="fa-solid fa-gift text-brand-orange"></i>
                <span>Aparatus Pastime Play Guarantee</span>
              </div>
              <p class="text-[11px] text-body-text font-sans">100% genuine toys &amp; active sports gear with doorstep support.</p>
            </div>
          </div>
        </div>

      </div>
    </div>
  </main>

  <footer class="bg-white border-t border-brand-border py-6 text-center text-xs text-brand-muted font-sans">
    <div class="max-w-7xl mx-auto px-4">
      <p>© {{ date('Y') }} Aparatus Pastime. All transactions are protected by bank-grade 256-bit encryption.</p>
    </div>
  </footer>

  <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
  <script>
    (function () {
      const csrf = document.querySelector('meta[name="csrf-token"]').content;
      const urls = {
        place:   @json(route('checkout.place')),
        rzpDone: @json(route('checkout.razorpay.success')),
        addrNew: @json(route('checkout.address.store')),
        addrDef: @json(route('checkout.address.default')),
        cities:  @json(url('checkout/cities')) + '/',
      };

      const form      = document.getElementById('checkout-form');
      const errBox    = document.getElementById('checkout-errors');
      const placeBtn  = document.getElementById('place-order-btn');
      const placeLbl  = document.getElementById('place-order-label');
      const newForm   = document.getElementById('new-address-form');
      const stateSel  = document.getElementById('state-select');
      const citySel   = document.getElementById('city-select');
      const hasSaved  = @json($hasAddresses);

      let selectedAddressId = @json($selectedAddressId);
      let usingNewForm = !hasSaved;

      // ── helpers ──────────────────────────────────────────────
      async function post(url, data) {
        const res = await fetch(url, {
          method: 'POST',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'X-CSRF-TOKEN': csrf,
            'X-Requested-With': 'XMLHttpRequest',
          },
          body: JSON.stringify(data),
        });
        let json = {};
        try { json = await res.json(); } catch (e) {}
        return { ok: res.ok, status: res.status, json };
      }

      function showErrors(messages) {
        const list = Array.isArray(messages) ? messages : [messages];
        errBox.innerHTML = list.map(m => `<div><i class="fa-solid fa-circle-exclamation mr-1"></i>${m}</div>`).join('');
        errBox.classList.remove('hidden');
        errBox.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }
      function clearErrors() { errBox.classList.add('hidden'); errBox.innerHTML = ''; }

      function flattenErrors(json) {
        if (json.errors) return Object.values(json.errors).flat();
        return [json.message || 'Something went wrong. Please try again.'];
      }

      function busy(on, label) {
        placeBtn.disabled = on;
        placeLbl.textContent = on ? (label || 'PROCESSING…') : 'COMPLETE & PLACE ORDER';
      }

      function newAddressData() {
        const fd = new FormData(form);
        return {
          name: fd.get('name'), email: fd.get('email'), phone: fd.get('phone'),
          address_line_1: fd.get('address_line_1'), address_line_2: fd.get('address_line_2'),
          state_id: fd.get('state_id'), city_id: fd.get('city_id'), pincode: fd.get('pincode'),
        };
      }

      // ── state → cities ───────────────────────────────────────
      stateSel?.addEventListener('change', async () => {
        citySel.innerHTML = '<option value="">Loading…</option>';
        if (!stateSel.value) { citySel.innerHTML = '<option value="">Select state first</option>'; return; }
        try {
          const res = await fetch(urls.cities + stateSel.value, { headers: { 'Accept': 'application/json' } });
          const cities = await res.json();
          citySel.innerHTML = '<option value="">Select city</option>' +
            cities.map(c => `<option value="${c.id}">${c.name}</option>`).join('');
        } catch (e) {
          citySel.innerHTML = '<option value="">Could not load cities</option>';
        }
      });

      // ── saved address selection ──────────────────────────────
      document.querySelectorAll('[data-address-card]').forEach(card => {
        card.addEventListener('click', async () => {
          const id = Number(card.dataset.id);
          if (id === selectedAddressId && !usingNewForm) return;

          selectedAddressId = id;
          usingNewForm = false;
          newForm.classList.add('hidden');

          card.querySelector('input[name="address_choice"]').checked = true;
          
          document.querySelectorAll('[data-address-card]').forEach(c => {
            c.className = 'block p-3 rounded-2xl border-2 cursor-pointer transition border-brand-border bg-white hover:border-brand-blue';
          });
          card.className = 'block p-3 rounded-2xl border-2 cursor-pointer transition border-brand-blue bg-soft-blue';

          // The default address drives GST, so persist it and reload to refresh totals
          const r = await post(urls.addrDef, { address_id: id });
          if (r.ok) window.location.reload();
          else showErrors(flattenErrors(r.json));
        });
      });

      document.getElementById('toggle-new-address')?.addEventListener('click', () => {
        usingNewForm = true;
        newForm.classList.remove('hidden');
        newForm.scrollIntoView({ behavior: 'smooth', block: 'center' });
      });
      document.getElementById('cancel-new-address')?.addEventListener('click', () => {
        usingNewForm = false;
        newForm.classList.add('hidden');
      });

      // Save new address now so GST in the summary updates
      document.getElementById('save-address-btn')?.addEventListener('click', async (e) => {
        clearErrors();
        const btn = e.currentTarget;
        btn.disabled = true;
        const r = await post(urls.addrNew, newAddressData());
        btn.disabled = false;
        if (r.ok && r.json.success) window.location.reload();
        else showErrors(flattenErrors(r.json));
      });

      // ── payment card highlight ───────────────────────────────
      document.querySelectorAll('input[name="payment_method"]').forEach(radio => {
        radio.addEventListener('change', () => {
          document.querySelectorAll('[data-pay-card]').forEach(l => {
            l.className = 'flex items-center justify-between p-3.5 rounded-2xl border border-brand-border bg-white hover:border-brand-blue cursor-pointer transition';
          });
          radio.closest('[data-pay-card]').className =
            'flex items-center justify-between p-3.5 rounded-2xl border-2 border-brand-orange bg-soft-orange cursor-pointer transition';
        });
      });

      // ── place order ──────────────────────────────────────────
      form.addEventListener('submit', async (e) => {
        e.preventDefault();
        clearErrors();

       const payload = { payment_method: form.querySelector('input[name="payment_method"]:checked').value };

const formVisible = !newForm.classList.contains('hidden');
const checkedCard = form.querySelector('input[name="address_choice"]:checked');

if (formVisible) {
  Object.assign(payload, newAddressData());      // customer is filling a new address
} else if (checkedCard) {
  payload.address_id = checkedCard.value;        // customer picked a saved address
} else {
  return showErrors('Please select or add a shipping address.');
}

        if (usingNewForm || !selectedAddressId) Object.assign(payload, newAddressData());
        else payload.address_id = selectedAddressId;

        busy(true, 'PLACING ORDER…');
        const r = await post(urls.place, payload);

        if (!r.ok || !r.json.success) {
          busy(false);
          return showErrors(flattenErrors(r.json));
        }

        // Cash on delivery: done
        if (r.json.type === 'cod') {
          window.location.href = r.json.redirect_url;
          return;
        }

        // Razorpay
        const d = r.json;
        const rzp = new Razorpay({
          key: d.key,
          amount: d.amount,
          currency: 'INR',
          name: 'Aparatus Pastime',
          description: 'Order payment',
          order_id: d.razorpay_order_id,
          prefill: { name: d.customer_name, email: d.customer_email, contact: d.customer_phone },
          theme: { color: '#F58220' },
          modal: { ondismiss: () => busy(false) },
          handler: async function (resp) {
            busy(true, 'CONFIRMING PAYMENT…');
            const v = await post(urls.rzpDone, {
              order_id: d.order_id,
              razorpay_payment_id: resp.razorpay_payment_id,
              razorpay_order_id: resp.razorpay_order_id,
              razorpay_signature: resp.razorpay_signature,
            });
            if (v.ok && v.json.success) window.location.href = v.json.redirect_url;
            else { busy(false); showErrors(flattenErrors(v.json)); }
          },
        });
        rzp.on('payment.failed', (resp) => {
          busy(false);
          showErrors(resp.error?.description || 'Payment failed. Please try again.');
        });
        rzp.open();
      });
    })();
  </script>
  </body>

</html>